name: Building LockLogger.apk with gradle

on:
  push:
    tag: "LockLogger.*.*"  

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: pwd
      - run: sudo apt update -y
      - run: sudo apt install curl openjdk-17-jdk unzip gradle -y
      - run: mkdir -p $HOME/android 
      - run: find .
      - run: curl -O https://dl.google.com/android/repository/commandlinetools-linux-13114758_latest.zip  
      - run: unzip commandlinetools-linux-13114758_latest.zip -d $HOME/android/
      - run: |
          export ANDROID_HOME=$HOME/android
          export ANDROID_SDK_ROOT=$ANDROID_HOME
          export PATH=$PATH:$ANDROID_HOME/cmdline-tools/bin:$ANDROID_HOME/platform-tools
          yes | sdkmanager --sdk_root=$ANDROID_HOME --licenses
          sdkmanager --sdk_root=$ANDROID_HOME "platform-tools" "platforms;android-34" "build-tools;34.0.0"
          ./gradlew :app:assembleDebug
      - uses: actions/upload-artifact@v4
        with:
          name: LockLogger.apk
          path: app/build/outputs/apk/debug/*.apk
      - uses: softprops/action-gh-release@v2
        with:
          name: LockLogger.apk
          file: app/build/outputs/apk/debug/*.apk 
        env:
          GN_TOKEN: ${{ secrets.GITHUB_TOKEN }}
