name: Building LockLogger.apk with gradle

on:
  push:
    branch: master

jobs:
  build:
    runs-on: ubuntu-latest
  # env:
  #   ANDROID_HOME: $HOME/android
  # permissions:
  #   contents: write
    steps:
      - uses: actions/checkout@v4
      - run: pwd
      - run: sudo apt update -y
      - run: sudo apt install curl openjdk-17-jdk unzip gradle -y
      - run: mkdir -p $HOME/android 
      - run: find .
      - run: curl -O https://dl.google.com/android/repository/commandlinetools-linux-13114758_latest.zip  
      - run: unzip commandlinetools-linux-13114758_latest.zip -d $HOME/android/
      # - run: |
            # echo "ANDROID_HOME=$HOME/android" >> $GITHUB_PATH
            # echo "PATH=$PATH:$ANDROID_HOME/cmdline-tools/bin:$ANDROID_HOME/platform-tools" >> $GITHUB_PATH 
            # echo "$ANDROID_HOME/platform-tools" >> $GITHUB_PATH
      - run: |
          export ANDROID_HOME=$HOME/android
          export PATH=$PATH:$ANDROID_HOME/cmdline-tools/bin:$ANDROID_HOME/platform-tools
          sdkmanager --sdk_root=$ANDROID_HOME --licenses
          sdkmanager --sdk_root=$ANDROID_HOME "platform-tools" "platforms;android-34" "build-tools;34.0.0"
          gradle assembleDebug
      - uses: actions/upload-artifact@v4
        with:
          name: LockLogger.apk
          path: app/build/outputs/apk/debug/*.apk
